name: 'sphinx-ape-action'
author: 'ApeWorX Ltd.'
description: 'Build Ape or plugins documentation'
branding:
  icon: 'book'
  color: 'green'

inputs:
  python-version:
    description: 'Override version of python, defaults to 3.10'
    required: false
    default: '3.10'
  github-token:
    description: 'Token for pushing to GitHub'
    required: false
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install
      run: |
        pip install git+https://github.com/ApeWorX/sphinx-ape.git@main
      shell: bash

    - name: Build Docs
      run: |
        sphinx-ape build . --mode "${{ github.event_name }}"
      shell: bash

    - name: Doctesting
      run: |
        sphinx-ape test .
      shell: bash

    - name: Commit and publish documentation changes to gh-pages branch
      run: |
        sphinx-ape publish . ${{ github.repository }} --cicd
      shell: bash
