name: 'sphinx-ape-action'
author: 'ApeWorX Ltd.'
description: 'Build Ape or plugins documentation'
branding:
  icon: 'book'
  color: 'green'

inputs:
  python-version:
    description: 'Override version of python, defaults to 3.10'
    required: false
    default: '3.10'
  github-token:
    description: 'Token for pushing to GitHub'
    required: false
    default: '3.10'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install
      run: |
        pip install git+https://github.com/ApeWorX/sphinx-ape.git@main
      shell: bash

    - name: Build Docs
      run: |
        sphinx-ape build . --mode "${{ github.event_name }}"
      shell: bash

    - name: Doctesting
      run: |
        sphinx-ape test .
      shell: bash

    - name: Commit and publish documentation changes to gh-pages branch
      if:  ${{ github.event_name }} != "pull_request"
      run: |
        # --skip-push assembles the build w/o pushing; for CI/CD.
        sphinx-ape publish . ${{ github.repository }} --skip-push
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
      shell: bash

    - name: Push changes
      if: ${{ github.event_name != 'pull_request' }}
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
